import enum


class MSM7200_NAND_FLASH_CMD_BITS_MASK(enum.Enum):
    READ_CACHE_LAST = (26, 0x1)
    READ_CACHE_SEQ = (25, 0x1)
    EN_READ_CACHE_NEXT_CMD = (24, 0x1)
    EN_PROGRAM_PAGE_CACHE_NEXT_CMD = (20, 0x1)
    EXTENDED_FETCH_ID = (19, 0x1)
    ONE_NAND_INTR_STATUS = (18, 0x1)
    ONE_NAND_HOST_CFG = (17, 0x1)
    AUTO_DETECT_DATA_XFR_SIZE = (7, 0x3ff)
    AUTO_DETECT = (6, 0x1)
    LAST_PAGE = (5, 0x1)
    PAGE_ACC = (4, 0x1)
    OP_CMD = (0, 0xf)


class MSM7200_NAND_FLASH_CMD_PAGE_ACC_VALUES(enum.Enum):
    NON_PAGE_ACCESS_COMMAND = 0
    PAGE_ACCESS_COMMAND = 1


class MSM7200_NAND_FLASH_CMD_OP_CMD_VALUES(enum.Enum):
    RESERVED_0 = 0
    ABORT_TRANSACTION = 1
    PAGE_READ = 2
    PAGE_READ_WITH_ECC = 3
    PAGE_READ_WITH_ECC_SPARE = 4
    PROGRAM_PAGE = 6
    PAGE_PROGRAM_WITH_ECC = 7
    RESERVED_8 = 8
    PROGRAM_PAGE_WITH_SPARE = 9
    BLOCK_ERASE = 10
    FETCH_ID = 11
    CHECK_STATUS = 12
    RESET_NAND_FLASH_DEVICE_OR_ONENAND_REGISTER_WRITE = 13
    RESERVED_E = 14
    RESERVED_F = 15


class MSM7200_NAND_ADDR0_BITS_MASK(enum.Enum):
    DEV_ADDR0 = (0, 0xffffffff)


class MSM7200_NAND_ADDR1_BITS_MASK(enum.Enum):
    DEV_ADDR1 = (0, 0xffffffff)


class MSM7200_NAND_FLASH_CHIP_SELECT_BITS_MASK(enum.Enum):
    RESET_XFR_STEP_LOAD_DONE_STATUS = (6, 0x1)
    XFR_STEP2_SAFE_REG_EN = (5, 0x1)
    ONE_NAND_EN = (3, 0x1)
    DM_EN = (2, 0x1)
    PARTIAL_XFR = (1, 0x1)
    NAND_DEV_SEL = (0, 0x1)


class MSM7200_NAND_FLASH_CHIP_SELECT_XFR_STEP2_SAFE_REG_EN_VALUES(enum.Enum):
    DYNAMICALLY_CHANGING_THE_XFR_STEP2_IS_ENABLED = 1


class MSM7200_NAND_FLASH_CHIP_SELECT_PARTIAL_XFR_VALUES(enum.Enum):
    DISABLE = 0
    ENABLE = 1


class MSM7200_NAND_FLASH_CHIP_SELECT_NAND_DEV_SEL_VALUES(enum.Enum):
    NAND_CS0_IS_SELECTED = 0
    NAND_CS1_IS_SELECTED = 1


class MSM7200_NANDC_EXEC_CMD_BITS_MASK(enum.Enum):
    EXEC_CMD = (0, 0x1)


class MSM7200_NANDC_EXEC_CMD_EXEC_CMD_VALUES(enum.Enum):
    EXECUTE_THE_COMMAND = 1


class MSM7200_NAND_FLASH_STATUS_BITS_MASK(enum.Enum):
    DEV_STATUS = (16, 0xffff)
    CODEWORD_CNTR = (12, 0xf)
    FIELD_2KBYTE_DEVICE = (11, 0x1)
    FIELD_512BYTE_DEVICE = (10, 0x1)
    AUTO_DETECT_DONE = (9, 0x1)
    MPU_ERROR = (8, 0x1)
    PROG_ERASE_OP_RESULT = (7, 0x1)
    NANDC_TIMEOUT_ERR = (6, 0x1)
    READY_BSY_N = (5, 0x1)
    OP_ERR = (4, 0x1)
    OPER_STATUS = (0, 0xf)


class MSM7200_NAND_FLASH_STATUS_FIELD_2KBYTE_DEVICE_VALUES(enum.Enum):
    NOT_A_2K_BYTE_PAGE_DEVICE = 0
    ENUM_2K_BYTE_PAGE_DEVICE = 1


class MSM7200_NAND_FLASH_STATUS_FIELD_512BYTE_DEVICE_VALUES(enum.Enum):
    NOT_A_512_BYTE_PAGE_DEVICE = 0
    ENUM_512_BYTE_PAGE_DEVICE = 1


class MSM7200_NAND_FLASH_STATUS_MPU_ERROR_VALUES(enum.Enum):
    NO_ERROR = 0
    MPU_ERROR_FOR_THE_ACCESS = 1


class MSM7200_NAND_FLASH_STATUS_NANDC_TIMEOUT_ERR_VALUES(enum.Enum):
    NO_ERROR = 0
    ERROR = 1


class MSM7200_NAND_FLASH_STATUS_READY_BSY_N_VALUES(enum.Enum):
    EXTERNAL_FLASH_IS_BUSY = 0
    EXTERNAL_FLASH_IS_READY = 1


class MSM7200_NAND_FLASH_STATUS_OPER_STATUS_VALUES(enum.Enum):
    IDLE_STATE = 0
    ABORT_TRANSACTION = 1
    PAGE_READ = 2
    PAGE_READ_WITH_ECC = 3
    PAGE_READ_WITH_ECC_AND_SPARE_DATA = 4
    SEQUENTIAL_PAGE_READ = 5
    PROGRAM_PAGE = 6
    PROGRAM_PAGE_WITH_ECC = 7
    RESERVED_PROGRAMMING = 8
    PROGRAM_PAGE_WITH_SPARE = 9
    BLOCK_ERASE = 10
    FETCH_ID = 11
    CHECK_STATUS = 12
    RESET_FLASH_DEVICE = 13


class MSM7200_NANDC_BUFFER_STATUS_BITS_MASK(enum.Enum):
    BAD_BLOCK_STATUS = (16, 0xffff)
    XFR_STEP2_REG_UPDATE_DONE = (9, 0x1)
    UNCORRECTABLE = (8, 0x1)
    NUM_ERRORS = (0, 0x1f)


class MSM7200_NAND_DEV_CFG0_BITS_MASK(enum.Enum):
    SET_RD_MODE_AFTER_STATUS = (31, 0x1)
    STATUS_BFR_READ = (30, 0x1)
    NUM_ADDR_CYCLES = (27, 0x7)
    SPARE_SIZE_BYTES = (23, 0xf)
    ECC_PARITY_SIZE_BYTES = (19, 0xf)
    UD_SIZE_BYTES = (9, 0x3ff)
    CW_PER_PAGE = (6, 0x7)
    ROW_ADDR_CYCLES = (3, 0x7)
    COL_ADDR_CYCLES = (0, 0x7)


class MSM7200_NAND_DEV_CFG0_NUM_ADDR_CYCLES_VALUES(enum.Enum):
    NO_ADDRESS_CYCLES = 0


class MSM7200_NAND_DEV_CFG0_CW_PER_PAGE_VALUES(enum.Enum):
    _1_CODEWORD_PER_PAGE = 0
    _2_CODEWORDS_PER_PAGE = 1
    _3_CODEWORDS_PER_PAGE = 2
    _4_CODEWORDS_PER_PAGE = 3
    _5_CODEWORDS_PER_PAGE = 4
    _6_CODEWORDS_PER_PAGE = 5
    _7_CODEWORDS_PER_PAGE = 6
    _8_CODEWORDS_PER_PAGE = 7


class MSM7200_NAND_DEV_CFG0_ROW_ADDR_CYCLES_VALUES(enum.Enum):
    NO_ROW_ADDRESS_CYCLES = 0


class MSM7200_NAND_DEV_CFG0_COL_ADDR_CYCLES_VALUES(enum.Enum):
    NO_COLUMN_ADDRESS_CYCLES = 0


class MSM7200_NAND_DEV_CFG1_BITS_MASK(enum.Enum):
    ECC_MODE = (28, 0x3)
    ENABLE_BCH_ECC = (27, 0x1)
    DISABLE_ECC_RESET_AFTER_OPDONE = (25, 0x1)
    ECC_DECODER_CGC_EN = (24, 0x1)
    ECC_ENCODER_CGC_EN = (23, 0x1)
    WR_RD_BSY_GAP = (17, 0x3f)
    BAD_BLOCK_IN_SPARE_AREA = (16, 0x1)
    BAD_BLOCK_BYTE_NUM = (6, 0x3ff)
    CS_ACTIVE_BSY = (5, 0x1)
    NAND_RECOVERY_CYCLES = (2, 0x7)
    WIDE_FLASH = (1, 0x1)
    ECC_DISABLE = (0, 0x1)


class MSM7200_NAND_DEV_CFG1_WR_RD_BSY_GAP_VALUES(enum.Enum):
    ENUM_2_CLOCK_CYCLE_GAP = 0
    ENUM_4_CLOCK_CYCLES_GAP = 1
    ENUM_6_CLOCK_CYCLES_GAP = 2
    ENUM_8_CLOCK_CYCLES_GAP = 3
    ENUM_10_CLOCK_CYCLES_GAP = 4
    ENUM_128_CLOCK_CYCLES_GAP = 63


class MSM7200_NAND_DEV_CFG1_BAD_BLOCK_IN_SPARE_AREA_VALUES(enum.Enum):
    IN_USER_DATA_AREA = 0
    IN_SPARE_AREA = 1


class MSM7200_NAND_DEV_CFG1_CS_ACTIVE_BSY_VALUES(enum.Enum):
    ALLOW_CS_DE_ASSERTION = 0
    ASSERT_CS_DURING_BUSY = 1


class MSM7200_NAND_DEV_CFG1_NAND_RECOVERY_CYCLES_VALUES(enum.Enum):
    ENUM_1_RECOVERY_CYCLE = 0
    ENUM_2_RECOVERY_CYCLES = 1
    ENUM_3_RECOVERY_CYCLES = 2
    ENUM_8_RECOVERY_CYCLES = 7


class MSM7200_NAND_DEV_CFG1_WIDE_FLASH_VALUES(enum.Enum):
    ENUM_8_BIT_DATA_BUS = 0
    ENUM_16_BIT_DATA_BUS = 1


class MSM7200_NAND_FLASH_READ_ID_BITS_MASK(enum.Enum):
    READ_ID = (0, 0xffffffff)


class MSM7200_NAND_FLASH_READ_STATUS_BITS_MASK(enum.Enum):
    ECC_STATUS = (16, 0xffff)
    DEV_STATUS = (0, 0xffff)


class MSM7200_NAND_FLASH_CONFIG_DATA_BITS_MASK(enum.Enum):
    DATA_IN = (0, 0xffffffff)


class MSM7200_NAND_FLASH_CONFIG_BITS_MASK(enum.Enum):
    DATA_OUT = (16, 0xffff)
    ADDR_OUT = (14, 0x3)
    DATA_OUT_EN = (13, 0x1)
    DATA_IN_EN = (10, 0x7)
    CS5_N = (9, 0x1)
    CS4_N = (8, 0x1)
    CS3_N = (7, 0x1)
    CS2_N = (6, 0x1)
    CS1_N = (5, 0x1)
    CS0_N = (4, 0x1)
    ALE = (3, 0x1)
    CLE = (2, 0x1)
    WE_N = (1, 0x1)
    RE_N = (0, 0x1)


class MSM7200_NAND_FLASH_CONFIG_DATA_IN_EN_VALUES(enum.Enum):
    DONT_READ = 0
    WRITE_NAND_FLASH_CONFIG_DATA_15_0 = 1
    WRITE_NAND_FLASH_CONFIG_DATA_31_16 = 2
    WRITE_NAND_FLASH_READ_STATUS_15_0 = 3


class MSM7200_NAND_FLASH_CONFIG_MODE_BITS_MASK(enum.Enum):
    CONFIG_ACC = (0, 0x1)


class MSM7200_NAND_FLASH_CONFIG_STATUS_BITS_MASK(enum.Enum):
    CONFIG_MODE = (0, 0x1)


class MSM7200_FLASH_MACRO1_REG_QSC6270_BITS_MASK(enum.Enum):
    ADDR_BUS_HOLD_CYCLE = (19, 0x1)
    DATA_START_ADDR = (0, 0xffff)


class MSM7200_FLASH_MACRO1_REG_BITS_MASK(enum.Enum):
    FLASH_DATA_MACRO1 = (14, 0x3f)
    FLASH_DATA_MACRO0 = (0, 0x3fff)


class MSM7200_FLASH_XFR_STEP_BITS_MASK(enum.Enum):
    CMD_SEQ_STEP_NUMBER = (30, 0x3)
    CMD_STEP1_WAIT = (26, 0xf)
    CMD_AOUT_EN = (25, 0x1)
    CMD_DATA_EN = (24, 0x1)
    CMD_CE_EN = (23, 0x1)
    CMD_CLE_EN = (22, 0x1)
    CMD_ALE_PIN = (21, 0x1)
    CMD_WE_EN = (20, 0x1)
    CMD_RE_EN = (19, 0x1)
    CMD_WIDE = (18, 0x1)
    DATA_SEQ_STEP_NUMBER = (14, 0x3)
    DATA_STEP1_WAIT = (10, 0xf)
    DATA_AOUT_EN = (9, 0x1)
    DATA_DATA_EN = (8, 0x1)
    DATA_CE_EN = (7, 0x1)
    DATA_CLE_EN = (6, 0x1)
    DATA_ALE_PIN = (5, 0x1)
    DATA_WE_EN = (4, 0x1)
    DATA_RE_EN = (3, 0x1)
    DATA_WIDE = (2, 0x1)
    EXTA_READ_WAIT = (0, 0x3)


class MSM7200_FLASH_XFR_STEP_CMD_SEQ_STEP_NUMBER_VALUES(enum.Enum):
    SIMPLE_STEP = 0
    LOOP_START = 1
    LOOP_END = 2
    LAST_STEP = 3


class MSM7200_FLASH_XFR_STEP_CMD_AOUT_EN_VALUES(enum.Enum):
    ADDRESS_LOGIC_DISABLED = 0
    DRIVE_ADDRESS = 1


class MSM7200_FLASH_XFR_STEP_CMD_DATA_EN_VALUES(enum.Enum):
    DISABLE_DATA_BUS = 0
    DRIVE_DATA = 1


class MSM7200_FLASH_XFR_STEP_CMD_CE_EN_VALUES(enum.Enum):
    DE_ASSERT_CHIP_SELECTS = 0
    ASSERT_CHIP_SELECT = 1


class MSM7200_FLASH_XFR_STEP_CMD_CLE_EN_VALUES(enum.Enum):
    LOGIC_DE_ASSERTS = 0
    LOGIC_ASSERTS = 1


class MSM7200_FLASH_XFR_STEP_CMD_ALE_PIN_VALUES(enum.Enum):
    LOGIC_DE_ASSERTS = 0
    LOGIC_ASSERTS = 1


class MSM7200_FLASH_XFR_STEP_CMD_WE_EN_VALUES(enum.Enum):
    LOGIC_DE_ASSERTS = 0
    LOGIC_ASSERTS = 1


class MSM7200_FLASH_XFR_STEP_CMD_RE_EN_VALUES(enum.Enum):
    LOGIC_DE_ASSERTS = 0
    LOGIC_ASSERTS = 1


class MSM7200_FLASH_XFR_STEP_CMD_WIDE_VALUES(enum.Enum):
    SEND_CMD_ON_8_BIT_BUS = 0
    SEND_CMD_ON_16_BIT_BUS = 1


class MSM7200_FLASH_XFR_STEP_DATA_SEQ_STEP_NUMBER_VALUES(enum.Enum):
    LOOP_START = 1
    LOOP_END = 2
    LAST_STEP = 3


class MSM7200_FLASH_XFR_STEP_DATA_AOUT_EN_VALUES(enum.Enum):
    ADDRESS_LOGIC_DISABLED = 0
    DRIVE_ADDRESS = 1


class MSM7200_FLASH_XFR_STEP_DATA_DATA_EN_VALUES(enum.Enum):
    DISABLE_DATA_BUS = 0
    DRIVE_DATA = 1


class MSM7200_FLASH_XFR_STEP_DATA_CE_EN_VALUES(enum.Enum):
    DE_ASSERT_CHIP_SELECTS = 0
    ASSERT_CHIP_SELECT = 1


class MSM7200_FLASH_XFR_STEP_DATA_CLE_EN_VALUES(enum.Enum):
    THE_LOGIC_DE_ASSERTS = 0
    THE_LOGIC_ASSERTS = 1


class MSM7200_FLASH_XFR_STEP_DATA_ALE_PIN_VALUES(enum.Enum):
    LOGIC_DE_ASSERTS = 0
    LOGIC_ASSERTS = 1


class MSM7200_FLASH_XFR_STEP_DATA_WE_EN_VALUES(enum.Enum):
    LOGIC_DE_ASSERTS = 0
    LOGIC_ASSERTS = 1


class MSM7200_FLASH_XFR_STEP_DATA_RE_EN_VALUES(enum.Enum):
    LOGIC_DE_ASSERTS = 0
    LOGIC_ASSERTS = 1


class MSM7200_FLASH_XFR_STEP_DATA_WIDE_VALUES(enum.Enum):
    USE_8_BIT_DATA_BUS_FOR_DATA = 0
    USE16_BIT_DATA_BUS_FOR_DATA = 1


class MSM7200_FLASH_DEV_CMD_BITS_MASK(enum.Enum):
    WRITE_START = (24, 0xff)
    WRITE_ADDR = (16, 0xff)
    ERASE_START = (8, 0xff)
    ERASE_ADDR = (0, 0xff)


class MSM7200_FLASH_DEV_CMD_VLD_BITS_MASK(enum.Enum):
    READ_PARAMETER_PAGE_CODE = (24, 0xff)
    SEQ_READ_START_VLD = (4, 0x1)
    ERASE_START_VLD = (3, 0x1)
    WRITE_START_VLD = (2, 0x1)
    READ_STOP_VLD = (1, 0x1)
    READ_START_VLD = (0, 0x1)


class MSM7200_EBI2_MISR_SIG_REG_BITS_MASK(enum.Enum):
    EBI2_MISR_SIG = (0, 0xffffffff)


class MSM7200_NAND_ADDR2_BITS_MASK(enum.Enum):
    DEV_ADDR2 = (0, 0xffffffff)


class MSM7200_NAND_ADDR3_BITS_MASK(enum.Enum):
    DEV_ADDR3 = (0, 0xffffffff)


class MSM7200_NAND_ADDR4_BITS_MASK(enum.Enum):
    DEV_ADDR4 = (0, 0xffffffff)


class MSM7200_NAND_ADDR5_BITS_MASK(enum.Enum):
    DEV_ADDR5 = (0, 0xffffffff)


class MSM7200_FLASH_DEV_CMD3_BITS_MASK(enum.Enum):
    READ_CACHE_LAST = (24, 0xff)
    READ_CACHE_SEQ = (16, 0xff)
    WRITE_START_CACHE = (0, 0xff)


class MSM7200_FLASH_DEV_CMD4_BITS_MASK(enum.Enum):
    GP_CMD4 = (16, 0xffff)
    GP_CMD3 = (0, 0xffff)


class MSM7200_FLASH_DEV_CMD5_BITS_MASK(enum.Enum):
    GP_CMD6 = (16, 0xffff)
    GP_CMD5 = (0, 0xffff)


class MSM7200_FLASH_DEV_CMD6_BITS_MASK(enum.Enum):
    GP_CMD8 = (16, 0xffff)
    GP_CMD7 = (0, 0xffff)


class MSM7200_NAND_ADDR6_BITS_MASK(enum.Enum):
    DEV_ADDR6 = (0, 0xffffffff)


class MSM7200_EBI2_ECC_BUF_CFG_BITS_MASK(enum.Enum):
    NUM_STEPS = (0, 0x3ff)


class MSM7200_FLASH_BUFF0_ACC_BITS_MASK(enum.Enum):
    BUFF_DATA = (0, 0xffffffff)
